telex:
  webhook_url: "https://ping.telex.im/v1/webhooks/01951f3f-d29a-75c2-acb9-d8b83553d2a5"

redis:
  host: "localhost:6379"

monitoring:
  memory_threshold: 104857600  # 100MB
  slow_log_threshold: 10
  cpu_threshold: 80.0
